name: "prjury meta reviewer"
description: "Aggregate silent adapter outputs and post a single PR review"
author: "prjury"
branding:
  icon: "check-circle"
  color: "blue"
inputs:
  github-token:
    description: "Token used for posting the unified review (GITHUB_TOKEN is fine)"
    required: true
  post-review:
    description: "If true, post a PR comment; otherwise only write report files"
    required: false
    default: "true"
  max-comments:
    description: "Maximum number of comments to emit (highest severity first)"
    required: false
    default: "15"
  input-dir:
    description: "Directory containing adapter JSON outputs"
    required: false
    default: "outputs"
  pr-number:
    description: "Explicit PR number (defaults to github.event.pull_request.number)"
    required: false
  openai-api-key:
    description: "Optional OpenAI API key to let the LLM rewrite/aggregate the comment"
    required: false
    default: ""
  openai-model:
    description: "OpenAI model name for aggregation (default gpt-4o-mini)"
    required: false
    default: "gpt-4o-mini"
  openai-base-url:
    description: "Override the OpenAI base URL (e.g., Azure/OpenRouter); defaults to https://api.openai.com/v1"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Ensure Node available
      shell: bash
      run: node -v

    - name: Run prjury
      shell: bash
      env:
        INPUT_DIR: ${{ inputs.input-dir }}
        OPENAI_KEY: ${{ inputs.openai-api-key }}
        OPENAI_MODEL: ${{ inputs.openai-model }}
        OPENAI_BASE_URL: ${{ inputs.openai-base-url }}
        PR_NUMBER: ${{ inputs.pr-number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        node "$GITHUB_ACTION_PATH/scripts/prjury.mjs" \
          --input "${INPUT_DIR}" \
          --max-comments "${{ inputs.max-comments }}" \
          --repo "${{ github.repository }}" \
          --pr "${PR_NUMBER:-${{ github.event.pull_request.number }}}" \
          --github-token "${GITHUB_TOKEN}" \
          --post "${{ inputs.post-review }}" \
          --openai-key "${OPENAI_KEY}" \
          --openai-model "${OPENAI_MODEL}" \
          --openai-base-url "${OPENAI_BASE_URL}"
